spring:
  messages:
    basename: "i18n/appmessages"
    encoding: "UTF-8"

questions:
  file-name: questions.csv

answers:
  file-name: answers.csv

student-test:
  pass-threshold: 4

localization:
    locale: ru_Ru